#* ************************************************************************** *#
#*                                                                            *#
#*                                                        :::      ::::::::   *#
#*   Makefile                                           :+:      :+:    :+:   *#
#*                                                    +:+ +:+         +:+     *#
#*   By: dwillems <dwillems@student.42.fr>          +#+  +:+       +#+        *#
#*                                                +#+#+#+#+#+   +#+           *#
#*   Created: 2015/12/24 12:51:51 by dwillems          #+#    #+#             *#
#*   Updated: 2015/12/28 19:13:38 by dwillems         ###   ########.fr       *#
#*                                                                            *#
#* ************************************************************************** *#

RESULT		=	galifrey
SOURCES		=	people.ml doctor.ml dalek.ml army.ml galifrey.ml main.ml

include OCamlMakefile
